name: learn_flutter_01
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.1.1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^6.0.0
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  scrollable_positioned_list: ^0.3.4
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    # To add custom fonts to your application
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
